In [2]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created using passed list:\n",a)

Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [4]:
import numpy as np
b=np.zeros((3,4))
print("\nAn array initialized with all zeroes:\n",b)


An array initialized with all zeroes:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
import numpy as np
c=np.full((3,3),6)
print("\nAn array iniyialized with all 6s.\n",c)


An array iniyialized with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [6]:
import numpy as np
d=np.random.random((2,2))
print("\nA random array:\n",d)


A random array:
 [[0.14737795 0.96076933]
 [0.33634231 0.79647876]]


In [8]:
import numpy as np
e=np.arange(0,30,5)
print("\n A sequential array with steps of 5:\n",e)


 A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [9]:
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\nOriginal array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [10]:
import numpy as np
flarr=arr.flatten()
print("\nOriginal array:\n",arr)
print("Flattened array:\n",flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [12]:
print("\nNo. of dimensions:",arr.ndim)


No. of dimensions: 2


In [13]:
print("\nShape of array:",arr.shape)


Shape of array: (3, 4)


In [14]:
print("\nSize of array:",arr.size)


Size of array: 12


In [15]:
print("\nArray stores elements of type: ",arr.dtype)


Array stores elements of type:  int32


In [16]:
newtype=arr.astype('f')
print("\nConverted array elements:\n",newtype)
print("Converted array type:",newtype.dtype)


Converted array elements:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
Converted array type: float32


In [1]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]


In [2]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[2,0:2])

[7 8]


In [5]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[2:,2:])

[[ 9]
 [12]
 [15]]


In [6]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:,3:])

[]


In [7]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[:,1])

[ 2  5  8 11 14]


In [8]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
c=p.astype('f')
print(c)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


In [9]:
import numpy as np
pp=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
c=p.astype('i')
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
