In [1]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("Original arrays:\n",a,b)
print("\nVector addition:\n",a+b)
print("\nVector subtraction:\n", a-b)
print("\nVector multiplication:\n",a*b)
print("\nVector division:\n",a/b)
print("\nVector Dot Product:\n",a.dot(b))
sclr=10
print("Scalar value=",sclr)
print("array=",a)
print("result=",a*sclr)



Original arrays:
 [10 20 30 40 50] [ 2  4  5  8 10]

Vector addition:
 [12 24 35 48 60]

Vector subtraction:
 [ 8 16 25 32 40]

Vector multiplication:
 [ 20  80 150 320 500]

Vector division:
 [5. 5. 6. 5. 5.]

Vector Dot Product:
 1070
Scalar value= 10
array= [10 20 30 40 50]
result= [100 200 300 400 500]


In [3]:
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
print("\nNumpy.Vectorize method")
print("\nReturn x-y if x>y,otherwise return x+y")
arr1=[10,4,20]
arr2=[2,3,30]
vec_func=np.vectorize(my_func)
print("Array 1:",arr1)
print("Array 2:",arr2)
print("result:",vec_func(arr1,arr2))




Numpy.Vectorize method

Return x-y if x>y,otherwise return x+y
Array 1: [10, 4, 20]
Array 2: [2, 3, 30]
result: [ 8  1 50]
